apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC/jCCAeagAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
    cm5ldGVzMB4XDTIyMDkyOTEzNDQwOFoXDTMyMDkyNjEzNDQwOFowFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALV8
    bFp6Ax4M3VdnO9jw6epgbwQfF+ciItvuv6wTcUu+SEqQ+JG07/4GUDrJhHWDeiFK
    R2atRQeLo9Jb7BSxZy0/DH8ucX16ucPen8jYFtD9r5JX883o2D2q/lcrlxSsloH1
    kHynZmqHeb9brvJI0yX96UeTq9obyl+OHCcbNBAfSCBk6nDbTBIB1jFsyV2DHWuV
    lFw5cXvXaW/Z6BoGkf28c7NrDL/U9rj/oeoyuFaPgj0C240OvxF588mdXJjScY+8
    FJ8UItx+S3eDeY4C+ONoel0k2TTM45uZuWpMkZECS74y46EojNcMbcu9JqG/cC2I
    pMSvPL6YrKwwdyIrN6UCAwEAAaNZMFcwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB
    /wQFMAMBAf8wHQYDVR0OBBYEFESeDM5KGx7jg0KMRqKYQh1Z+60oMBUGA1UdEQQO
    MAyCCmt1YmVybmV0ZXMwDQYJKoZIhvcNAQELBQADggEBAE5lA3kSXtj2kuXJixE/
    Wo5Hz0mEcr175zBMRhflTai5+2gOW9xYvVhq0lVaz0N5ik/4tVKsMEGv+rG3AIcy
    upFbUEctORmiOcKHqv9szf7MYdZOB9BIsfdHEEhaY5jPjjqMCjIr/t9GDW/wVrCB
    Xf4slz24KwQSyuhN5ZNN51iIbpXauFfzym8RsFy3aGgx1U2VjMVSucs8j+K1qwsD
    G1enrF0ESInPOUrGMUk1BCzaGrX+ALP9HaCGet4emVy288LZSYqXTdU5A1yJb4zo
    1OmGBFWnYy2zyO44A9KGNY7M2t0sdCVEj54BM/BDLqQjgQtHTmSm3PpuRBYXYaJO
    chk=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  creationTimestamp: "2022-09-29T13:44:43Z"
  name: kube-root-ca.crt
  namespace: kube-public
  resourceVersion: "348"
  uid: ed712005-b130-41e1-856b-f71d8d889a56
